sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - "6"
  - "8"
  - "9"
install: npm install
before_script:
  - npm prune
script:
  - yarn test
  - yarn build
after_success:
  - yarn report-coverage
