sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - "6"
  - "8"
  - "9"
  - "10"
install: yarn install
script:
  - yarn run test
  - yarn run build
after_success:
  - yarn run report-coverage
