sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - "6"
  - "8"
  - "9"
  - "10"
install: npm install
before_script:
  - npm prune
script:
  - npm run test
  - npm run build
after_success:
  - npm run report-coverage
